# Generated by Django 4.0.4 on 2022-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=122)),
                ('incident_department', models.TextField()),
                ('date', models.DateField()),
                ('incident_location', models.TextField()),
                ('initial_severity', models.CharField(max_length=122)),
                ('suspected_cause', models.TextField()),
                ('immediate_action_taken', models.TextField()),
                ('sub_incident_type', models.CharField(max_length=122)),
            ],
        ),
    ]
