# Generated by Django 4.0.4 on 2022-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='initial_severity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sub_incident_type',
            field=models.TextField(),
        ),
    ]
