# Generated by Django 4.0.4 on 2022-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_incident_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=22),
        ),
    ]
